import ReactMarkdown from "react-markdown";

export default function NotesViewer({ notes }) {
  return (
    <div className="w-full rounded-2xl border border-white/20 bg-black/55 backdrop-blur-xl shadow-2xl overflow-hidden">
      
      {/* Header */}
      <div className="px-6 py-4 border-b border-white/20 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-white">
            Generated Notes
          </h2>
          <p className="text-sm text-slate-300">
            Structured, exam-ready content generated by AI
          </p>
        </div>

        <span className="px-3 py-1 text-xs rounded-full bg-indigo-500/25 text-indigo-200 border border-indigo-400/40">
          AI Output
        </span>
      </div>

      {/* Content – NO INTERNAL SCROLL */}
      <div className="px-6 py-8 flex justify-center">
        <div
          className="
            w-full max-w-3xl

            /* Base text */
            [&*]:text-slate-100

            /* Headings */
            [&_h1]:text-white [&_h2]:text-white [&_h3]:text-white
            [&_h1]:text-2xl [&_h2]:text-xl [&_h3]:text-lg
            [&_h1,&_h2,&_h3]:font-semibold
            [&_h1,&_h2,&_h3]:mt-10
            [&_h1,&_h2,&_h3]:mb-4

            /* Paragraphs */
            [&_p]:leading-relaxed
            [&_p]:mb-4

            /* Lists */
            [&_ul]:mb-4
            [&_ol]:mb-4
            [&_li]:mb-2
            [&_li::marker]:text-indigo-400

            /* Links */
            [&_a]:text-indigo-300
            [&_a]:underline
            [&_a:hover]:text-indigo-200

            /* Inline code */
            [&_code]:text-indigo-200
            [&_code]:bg-black/70
            [&_code]:px-1.5
            [&_code]:py-0.5
            [&_code]:rounded-md

            /* Code blocks */
            [&_pre]:bg-black/70
            [&_pre]:border
            [&_pre]:border-white/20
            [&_pre]:rounded-xl
            [&_pre]:p-4
            [&_pre]:my-6
            [&_pre_code]:text-slate-100

            /* Blockquotes */
            [&_blockquote]:border-l-4
            [&_blockquote]:border-indigo-500
            [&_blockquote]:bg-black/40
            [&_blockquote]:px-5
            [&_blockquote]:py-3
            [&_blockquote]:rounded-r-lg
            [&_blockquote]:my-6

            /* Tables */
            [&_table]:w-full
            [&_table]:my-6
            [&_table]:border-collapse
            [&_table]:border [&_table]:border-white/20
            [&_th]:bg-black/60
            [&_th,&_td]:border [&_th,&_td]:border-white/20
            [&_th,&_td]:px-3 [&_th,&_td]:py-2

            /* Horizontal rule */
            [&_hr]:my-8
            [&_hr]:border-white/30
          "
        >
          <ReactMarkdown>{notes}</ReactMarkdown>
        </div>
      </div>

      {/* Footer */}
      <div className="px-6 py-3 border-t border-white/20 text-xs text-slate-300 flex justify-between">
        
      </div>
    </div>
  );
}
